### ISSUE TITLE
Video upload error

### ISSUE THREAD

**Issue by crossle** [MixinNetwork/android-app#1423]
1. Some videos convert error
2. Attachment add upload and download speed 
3. If send video failed, should report the error and show to the user

**Comment by SeniorZhai** [comment]
Fix video lost audio #1458

**Comment by SeniorZhai** [comment]
Upload attachments using OKHTTP #1626

**Comment by SeniorZhai** [comment]
Show covert progress #1611

**Comment by crossle** [comment]
```
                         E  java.net.ProtocolException: unexpected end of stream
                         E      at okhttp3.internal.connection.Exchange$RequestBodySink.close(Exchange.kt:239)
                         E      at okio.RealBufferedSink.close(RealBufferedSink.kt:286)
                         E      at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:60)
                         E      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                         E      at com.android.tools.profiler.agent.okhttp.OkHttp3Interceptor.intercept(OkHttp3Interceptor.java:57)
                         E      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                         E      at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
                         E      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                         E      at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
                         E      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                         E      at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
                         E      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                         E      at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
                         E      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                         E      at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
                         E      at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
                         E      at one.mixin.android.crypto.Util.uploadAttachment(Util.java:100)
                         E      at one.mixin.android.job.SendAttachmentMessageJob.uploadAttachment(SendAttachmentMessageJob.kt:208)
                         E      at one.mixin.android.job.SendAttachmentMessageJob.processAttachment(SendAttachmentMessageJob.kt:162)
                         E      at one.mixin.android.job.SendAttachmentMessageJob.access$processAttachment(SendAttachmentMessageJob.kt:32)
                         E      at one.mixin.android.job.SendAttachmentMessageJob$onRun$1.apply(SendAttachmentMessageJob.kt:94)
                         E      at one.mixin.android.job.SendAttachmentMessageJob$onRun$1.apply(SendAttachmentMessageJob.kt:32)
                         E      at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:57)
                         E      at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:54)
                         E      at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:38)
                         E      at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:48)
                         E      at io.reactivex.Observable.subscribe(Observable.java:12284)
                         E      at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:35)
                         E      at io.reactivex.Observable.subscribe(Observable.java:12284)
                         E      at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
                         E      at io.reactivex.Observable.subscribe(Observable.java:12284)
                         E      at io.reactivex.Observable.subscribe(Observable.java:12270)
                         E      at io.reactivex.Observable.subscribe(Observable.java:12198)
                         E      at one.mixin.android.job.SendAttachmentMessageJob.onRun(SendAttachmentMessageJob.kt:98)
                         E      at com.birbit.android.jobqueue.Job.safeRun(Job.java:229)
                         E      at com.birbit.android.jobqueue.JobHolder.safeRun(JobHolder.java:132)
                         E      at com.birbit.android.jobqueue.ConsumerManager$Consumer.handleRunJob(ConsumerManager.java:413)
                         E      at com.birbit.android.jobqueue.ConsumerManager$Consumer.access$000(ConsumerManager.java:333)
                         E      at com.birbit.android.jobqueue.ConsumerManager$Consumer$2.handleMessage(ConsumerManager.java:361)
                         E      at com.birbit.android.jobqueue.messaging.SafeMessageQueue.consume(SafeMessageQueue.java:36)
                         E      at com.birbit.android.jobqueue.ConsumerManager$Consumer.run(ConsumerManager.java:395)
                         E      at java.lang.Thread.run(Thread.java:923)
```
